# Fritz!Box Spectrum Logger (https://github.com/c-mueller/fritzbox-spectrum-logger).
# Copyright (c) 2018 Christian Müller <cmueller.dev@gmail.com>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
workspace:
  base: /go
  path: src/github.com/c-mueller/fritzbox-spectrum-logger

pipeline:
  build_ui:
    image: halive/random-images:angular-cli-v6-beta6
    commands:
      # Build the UI
      - cd ui
      - yarn install
      - ng build --prod
      # Copy built artifact for static linking
      - cd dist
      - cp -r * ../../server/ui-dist
  load_deps:
    image: golang:${GO_VERSION}
    commands:
      # Install Fish shell
      - apt-get update && apt-get install -y fish
      # Install Rice
      - go get github.com/GeertJohan/go.rice
      - go get github.com/GeertJohan/go.rice/rice
      # Install Godep
      - go get -u github.com/golang/dep/cmd/dep
      # Install Dependencies
      - ./update_deps.fish
      # Compile static dependency file
      - ./embed_resources.fish
      # Build the Application
      - ./build.fish
  test_and_benchmark:
    image: golang:${GO_VERSION}
    commands:
      - go test -v -cover -bench=. -benchtime=1s ./...
  cloc_report:
    image: halive/git-cloc:latest
    commands:
      - cloc $(git ls-files)
  application_version_info:
    image: ubuntu:16.04
    commands:
      - cp fritzbox-spectrum-logger /usr/bin/
      - fritzbox-spectrum-logger version
  publish_docker_image:
    image: plugins/docker
    repo: halive/fsl
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - fritzbox-spectrum-logger
    checksum:
      - sha256
      - sha512
    when:
      event: tag

matrix:
  GO_VERSION:
    - "1.10"
#    - "1.9"
