FROM ubuntu:18.04

WORKDIR /fsl

VOLUME /fsl/data

ENV DB_PATH="/fsl/data/spectra.db"
ENV AUTOLAUNCH="false"
ENV ENDPOINT_URL=":80"

ENV FRITZ_ENDPOINT="192.168.178.1"
ENV FRITZ_USERNAME=""
ENV FRITZ_PASSWORD=""
ENV UPDATE_INTERVAL="60"
ENV SESSION_REFRESH_INTERVAL="3600"
ENV SESSION_REFRESH_ATTEMPTS="5"
ENV MAX_DOWNLOAD_FAILS="5"

ADD fritzbox-spectrum-logger /usr/bin/fsl

EXPOSE 80
CMD fsl server env -d